# Generated by Django 2.0.3 on 2018-11-08 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='extra_cheese',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs_extra_cheese', to='orders.ExtraCheese'),
        ),
    ]
