# Generated by Django 2.0.3 on 2018-11-08 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20181108_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='extra_cheese',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subs_extra_cheese', to='orders.ExtraCheese'),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_price', to='orders.Price'),
        ),
        migrations.AlterField(
            model_name='food',
            name='select_toppings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pizza_topping_number', to='orders.ToppingNumber'),
        ),
        migrations.AlterField(
            model_name='food',
            name='size',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_size', to='orders.Size'),
        ),
        migrations.AlterField(
            model_name='food',
            name='toppings',
            field=models.ManyToManyField(blank=True, null=True, related_name='pizza_topping', to='orders.Topping'),
        ),
        migrations.AlterField(
            model_name='food',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pizza_type', to='orders.PizzaType'),
        ),
    ]
