# Generated by Django 2.0.3 on 2018-11-08 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20181108_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='size',
            field=models.ForeignKey(blank=True, default='one size', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_size', to='orders.Size'),
        ),
    ]
