# Generated by Django 2.0.3 on 2018-11-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20181109_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='topping',
            name='topping',
            field=models.CharField(max_length=64, verbose_name='list of toppings'),
        ),
    ]
