# Generated by Django 2.0.3 on 2018-11-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20181109_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='topping',
            name='topping',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='toppingnumber',
            name='number',
            field=models.CharField(max_length=64, verbose_name='Number of toppings'),
        ),
    ]
