# Generated by Django 2.0.3 on 2018-11-16 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0008_auto_20181115_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toppings', models.CharField(choices=[('NONE', 'None'), ('PEPPERONI', 'Pepperoni'), ('SAUSAGE', 'Sausage'), ('MUSHROOMS', 'Mushrooms'), ('ONIONS', 'Onions'), ('HAM', 'Ham'), ('CANADIAN BACON', 'Canadian Bacon'), ('PINEAPPLE', 'Pineapple'), ('EGGPLANT', 'Egglplant'), ('TOMATO & BASIL', 'Tomato & Basil'), ('GREEN PEPPERS', 'Green Peppers'), ('HAMBURGER', 'Hamburger'), ('SPINACH', 'Spinach'), ('ARTICHOKE', 'Artichoke'), ('BUFFALO CHICKEN', 'Buffalo Chicken'), ('BARBECUE CHICKEN', 'Barbecue Chicken'), ('ANCHOVIES', 'Anchovies'), ('BLACK OLIVES', 'Black Olives'), ('FRESH GARLIC', 'Fresh Garlic'), ('ZUCCHINI', 'Zucchini')], default='NONE', max_length=50)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_food', to='orders.Food')),
                ('order_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.OrderNumber')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_price', to='orders.Food')),
                ('select_toppings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_topping_number', to='orders.Food')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_size', to='orders.Food')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_type', to='orders.Food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
