# Generated by Django 2.0.3 on 2018-11-16 07:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0009_ordernumber_orderpizza'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderPizza',
            new_name='Order',
        ),
    ]
