# Generated by Django 2.0.3 on 2018-11-16 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20181116_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='select_toppings',
        ),
        migrations.RemoveField(
            model_name='order',
            name='size',
        ),
        migrations.RemoveField(
            model_name='order',
            name='type',
        ),
    ]
