# Generated by Django 2.0.3 on 2018-11-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
    ]
