# Generated by Django 2.0.3 on 2018-11-17 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20181118_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='toppings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizza_toppings', to='orders.Topping'),
        ),
    ]
