# Generated by Django 2.0.3 on 2018-11-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20181118_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='toppings',
        ),
        migrations.AddField(
            model_name='food',
            name='toppings',
            field=models.ManyToManyField(blank=True, null=True, related_name='pizza_topping', to='orders.Topping'),
        ),
    ]
