# Generated by Django 2.0.3 on 2018-11-18 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20181118_0145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='toppings',
        ),
    ]
