# Generated by Django 2.0.3 on 2018-11-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_remove_food_toppings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='toppings',
        ),
        migrations.RemoveField(
            model_name='topping',
            name='topping',
        ),
        migrations.AddField(
            model_name='topping',
            name='topping',
            field=models.ManyToManyField(blank=True, related_name='toppings', to='orders.Order'),
        ),
    ]
