# Generated by Django 2.0.3 on 2018-11-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20181119_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topping',
            old_name='topping',
            new_name='order',
        ),
        migrations.AddField(
            model_name='topping',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
