# Generated by Django 2.0.3 on 2018-11-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_auto_20181122_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='topping',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='extra_cheese',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='pizza', to='orders.Topping'),
        ),
        migrations.AddField(
            model_name='order',
            name='extra_sub',
            field=models.ManyToManyField(blank=True, related_name='subs', to='orders.ExtraSub'),
        ),
    ]
