# Generated by Django 2.0.3 on 2018-11-22 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_auto_20181122_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='extra_cheese',
            new_name='extra',
        ),
    ]
