# Generated by Django 2.0.3 on 2018-11-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='extra',
            field=models.BooleanField(default=False),
        ),
    ]
