# Generated by Django 2.0.3 on 2018-11-28 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0030_food_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernumber',
            name='date',
            field=models.DateTimeField(default='2018-11-28 22:29:03.126771+00:00'),
        ),
        migrations.AddField(
            model_name='ordernumber',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordernumber',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='ordernumber',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
