# Generated by Django 2.0.3 on 2018-11-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_auto_20181129_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordernumber',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
