# Generated by Django 2.0.3 on 2018-11-28 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_auto_20181129_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordernumber',
            name='user',
        ),
        migrations.AddField(
            model_name='ordernumber',
            name='username',
            field=models.CharField(default='', max_length=64),
        ),
    ]
