# Generated by Django 2.0.3 on 2018-11-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_auto_20181129_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernumber',
            name='in_cart',
            field=models.BooleanField(default=True),
        ),
    ]
