# Generated by Django 2.0.3 on 2018-11-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_auto_20181129_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordernumber',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
