# Generated by Django 2.0.3 on 2018-11-30 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_auto_20181130_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernumber',
            name='in_process',
            field=models.BooleanField(default=True),
        ),
    ]
