# Generated by Django 2.0.3 on 2018-12-01 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_auto_20181201_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='topping_number',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
