# Generated by Django 2.0.3 on 2018-12-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0043_auto_20181203_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernumber',
            name='email',
            field=models.CharField(default='', max_length=64),
        ),
    ]
