# Generated by Django 2.0.3 on 2018-12-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0044_ordernumber_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordernumber',
            name='email',
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(default='', max_length=64),
        ),
    ]
