# Generated by Django 2.0.3 on 2018-12-22 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0045_auto_20181223_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
    ]
